// This file has been generated by Py++.

#ifndef cxcore_hpp_point_ext_classes_3_hpp__pyplusplus_wrapper
#define cxcore_hpp_point_ext_classes_3_hpp__pyplusplus_wrapper

void register_classes_3();

#endif//cxcore_hpp_point_ext_classes_3_hpp__pyplusplus_wrapper
