// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "cxflann_h_wrapper.hpp"
#include "__cxflann_h_dummy_struct.pypp.hpp"

namespace bp = boost::python;

void register___cxflann_h_dummy_struct_class(){

    { //::cxflann_h_dummy_struct
        typedef bp::class_< cxflann_h_dummy_struct > __cxflann_h_dummy_struct_exposer_t;
        __cxflann_h_dummy_struct_exposer_t __cxflann_h_dummy_struct_exposer = __cxflann_h_dummy_struct_exposer_t( "__cxflann_h_dummy_struct" );
        bp::scope __cxflann_h_dummy_struct_scope( __cxflann_h_dummy_struct_exposer );
        __cxflann_h_dummy_struct_exposer.add_property( "this", pyplus_conv::make_addressof_inst_getter< cxflann_h_dummy_struct >() );
        bp::class_< cxflann_h_dummy_struct::dummy_struct2 >( "dummy_struct2" )    
            .add_property( "this", pyplus_conv::make_addressof_inst_getter< cxflann_h_dummy_struct::dummy_struct2 >() );
        __cxflann_h_dummy_struct_exposer.setattr("v0", 0);
    }
    {;
    }

}
