#ifndef SD_ml_TEMPLATE_INSTANTIATIONS_HPP
#define SD_ml_TEMPLATE_INSTANTIATIONS_HPP

class ml_dummy_struct {
public:
    struct dummy_struct2 {};
    static const int total_size = 0
        + sizeof(cv::Point3_<double>)
        + sizeof(cv::Point3_<float>)
        + sizeof(cv::Point3_<int>)
        + sizeof(cv::Point_<double>)
        + sizeof(cv::Point_<float>)
        + sizeof(cv::Point_<int>)
        + sizeof(cv::Rect_<int>)
        + sizeof(cv::Size_<int>)
        + sizeof(cv::Vec<double,2>)
        + sizeof(cv::Vec<double,3>)
        + sizeof(cv::Vec<double,4>)
        + sizeof(cv::Vec<double,6>)
        + sizeof(cv::Vec<float,2>)
        + sizeof(cv::Vec<float,3>)
        + sizeof(cv::Vec<float,4>)
        + sizeof(cv::Vec<float,6>)
        + sizeof(cv::Vec<int,2>)
        + sizeof(cv::Vec<int,3>)
        + sizeof(cv::Vec<int,4>)
        + sizeof(cv::Vec<short,2>)
        + sizeof(cv::Vec<short,3>)
        + sizeof(cv::Vec<short,4>)
        + sizeof(cv::Vec<unsigned char,2>)
        + sizeof(cv::Vec<unsigned char,3>)
        + sizeof(cv::Vec<unsigned char,4>)
        + sizeof(cv::Vec<unsigned short,2>)
        + sizeof(cv::Vec<unsigned short,3>)
        + sizeof(cv::Vec<unsigned short,4>)
        + sizeof(std::vector<cv::Mat>)
        + sizeof(std::vector<cv::MatND>)
        + sizeof(std::vector<cv::Point3_<double> >)
        + sizeof(std::vector<cv::Point3_<float> >)
        + sizeof(std::vector<cv::Point3_<int> >)
        + sizeof(std::vector<cv::Point_<double> >)
        + sizeof(std::vector<cv::Point_<float> >)
        + sizeof(std::vector<cv::Point_<int> >)
        + sizeof(std::vector<cv::Rect_<int> >)
        + sizeof(std::vector<cv::Vec<double,2> >)
        + sizeof(std::vector<cv::Vec<double,3> >)
        + sizeof(std::vector<cv::Vec<double,4> >)
        + sizeof(std::vector<cv::Vec<double,6> >)
        + sizeof(std::vector<cv::Vec<float,2> >)
        + sizeof(std::vector<cv::Vec<float,3> >)
        + sizeof(std::vector<cv::Vec<float,4> >)
        + sizeof(std::vector<cv::Vec<float,6> >)
        + sizeof(std::vector<cv::Vec<int,2> >)
        + sizeof(std::vector<cv::Vec<int,3> >)
        + sizeof(std::vector<cv::Vec<int,4> >)
        + sizeof(std::vector<cv::Vec<short,2> >)
        + sizeof(std::vector<cv::Vec<short,3> >)
        + sizeof(std::vector<cv::Vec<short,4> >)
        + sizeof(std::vector<cv::Vec<unsigned char,2> >)
        + sizeof(std::vector<cv::Vec<unsigned char,3> >)
        + sizeof(std::vector<cv::Vec<unsigned char,4> >)
        + sizeof(std::vector<cv::Vec<unsigned short,2> >)
        + sizeof(std::vector<cv::Vec<unsigned short,3> >)
        + sizeof(std::vector<cv::Vec<unsigned short,4> >)
        + sizeof(std::vector<float>)
        + sizeof(std::vector<int>)
        + sizeof(std::vector<std::vector<cv::Point3_<double> > >)
        + sizeof(std::vector<std::vector<cv::Point3_<float> > >)
        + sizeof(std::vector<std::vector<cv::Point3_<int> > >)
        + sizeof(std::vector<std::vector<cv::Point_<double> > >)
        + sizeof(std::vector<std::vector<cv::Point_<float> > >)
        + sizeof(std::vector<std::vector<cv::Point_<int> > >)
        + sizeof(std::vector<unsigned char>)
        + sizeof(std::vector<unsigned int>);
};

#endif
