// This file has been generated by Py++.

#ifndef vector_Vec4d_hpp__pyplusplus_wrapper
#define vector_Vec4d_hpp__pyplusplus_wrapper

void register_vector_Vec4d_class();

#endif//vector_Vec4d_hpp__pyplusplus_wrapper
