// This file has been generated by Py++.

#ifndef CvString_hpp__pyplusplus_wrapper
#define CvString_hpp__pyplusplus_wrapper

void register_CvString_class();

#endif//CvString_hpp__pyplusplus_wrapper
