// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "opencv_headers.hpp"
#include "vector_Size2i.pypp.hpp"

namespace bp = boost::python;

static inline void resize(::std::vector< cv::Size_<int> > &inst, size_t num) { inst.resize(num); }

void register_vector_Size2i_class(){

    { //::std::vector< cv::Size_<int> >
        typedef bp::class_< std::vector< cv::Size_<int> > > vector_Size2i_exposer_t;
        vector_Size2i_exposer_t vector_Size2i_exposer = vector_Size2i_exposer_t( "vector_Size2i" );
        bp::scope vector_Size2i_scope( vector_Size2i_exposer );
        //WARNING: the next line of code will not compile, because "::cv::Size_<int>" does not have operator== !
        vector_Size2i_exposer.def( bp::vector_indexing_suite< ::std::vector< cv::Size_<int> > >() );
        vector_Size2i_exposer.def("resize", &::resize, ( bp::arg("num") ));
    }

}
