// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "opencv_headers.hpp"
#include "CvTermCriteria.pypp.hpp"

namespace bp = boost::python;

void register_CvTermCriteria_class(){

    bp::class_< CvTermCriteria >( "CvTermCriteria", "\nTermination criteria for iterative algorithms."
    "\nReference:"
    "\n    http://opencv.willowgarage.com/documentation/basic_structures.html#cvtermcriteria" )    
        .add_property( "this", pyplus_conv::make_addressof_inst_getter< CvTermCriteria >(), "\nTermination criteria for iterative algorithms."
    "\nReference:"
    "\n    http://opencv.willowgarage.com/documentation/basic_structures.html#cvtermcriteria" )    
        .def_readwrite( "epsilon", &CvTermCriteria::epsilon )    
        .def_readwrite( "max_iter", &CvTermCriteria::max_iter )    
        .def_readwrite( "type", &CvTermCriteria::type );

}
