// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "opencv_headers.hpp"
#include "fernclassifier.pypp.hpp"

namespace bp = boost::python;

void register_FernClassifier_class(){

    bp::class_< cv::FernClassifier >( "FernClassifier" )    
        .add_property( "this", pyplus_conv::make_addressof_inst_getter< cv::FernClassifier >() );

}
