// This file has been generated by Py++.

#ifndef Vector_Vector_Vec2f_hpp__pyplusplus_wrapper
#define Vector_Vector_Vec2f_hpp__pyplusplus_wrapper

void register_Vector_Vector_Vec2f_class();

#endif//Vector_Vector_Vec2f_hpp__pyplusplus_wrapper
