// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "opencv_headers.hpp"
#include "OneWayDescriptor.pypp.hpp"

namespace bp = boost::python;

void register_OneWayDescriptor_class(){

    bp::class_< cv::OneWayDescriptor >( "OneWayDescriptor" )    
        .add_property( "this", pyplus_conv::make_addressof_inst_getter< cv::OneWayDescriptor >() );

}
