#ifndef SD_TEMPLATE_INSTANTIATIONS_H
#define SD_TEMPLATE_INSTANTIATIONS_H

struct dummy_struct3 {
    struct dummy_struct2 {};
    cv::Vec< unsigned char, 3 > var0;
    std::vector< cv::CascadeClassifier::DTree > var1;
    std::vector< std::vector< cv::Vec< unsigned short, 3 > > > var2;
    std::vector< double > var4;
    std::vector< std::vector< cv::Vec< int, 2 > > > var5;
    std::vector< float > var6;
    std::vector< cv::Point3_< float > > var8;
    std::vector< cv::Vec< double, 3 > > var9;
    std::vector< cv::Vec< double, 2 > > var10;
    cv::Size_< int > var14;
    cv::Vec< float, 6 > var15;
    std::vector< cv::Vec< float, 2 > > var19;
    std::vector< std::vector< cv::Point3_< int > > > var20;
    std::vector< unsigned char * > var21;
    std::vector< cv::KeyPoint > var23;
    cv::Vec< short, 2 > var25;
    std::vector< cv::CascadeClassifier::Stage > var26;
    std::vector< cv::Vec< float, 4 > > var28;
    cv::Vec< int, 3 > var29;
    cv::Vec< short, 4 > var30;
    std::vector< cv::MatND > var31;
    std::vector< cv::Point3_< double > > var33;
    cv::Vec< unsigned short, 4 > var34;
    std::vector< cv::Vec< unsigned short, 4 > > var35;
    std::vector< cv::FernClassifier::Feature > var36;
    std::vector< cv::Point_< float > > var37;
    std::vector< std::vector< cv::Vec< float, 3 > > > var38;
    std::vector< std::vector< cv::Vec< unsigned short, 4 > > > var39;
    std::vector< unsigned short > var40;
    cv::Size_< float > var41;
    cv::Vec< double, 4 > var42;
    std::vector< std::vector< cv::Vec< unsigned short, 2 > > > var45;
    std::vector< std::vector< cv::Vec< short, 2 > > > var47;
    std::vector< std::vector< cv::Point3_< float > > > var50;
    std::vector< CvFuzzyPoint > var53;
    std::vector< cv::Vec< double, 6 > > var54;
    cv::Complex< double > var56;
    std::vector< std::vector< cv::Point_< int > > > var60;
    cv::Point_< double > var62;
    std::vector< cv::Vec< double, 4 > > var65;
    cv::Ptr< cv::Mat > var66;
    cv::Point3_< float > var67;
    std::vector< cv::Vec< float, 3 > > var69;
    cv::Vec< unsigned char, 2 > var70;
    std::vector< std::vector< cv::Vec< double, 2 > > > var71;
    cv::Vec< float, 2 > var73;
    cv::Vec< short, 3 > var74;
    std::vector< std::vector< cv::Vec< int, 4 > > > var76;
    std::vector< cv::Vec< int, 3 > > var78;
    std::vector< cv::Vec< unsigned char, 4 > > var79;
    std::vector< cv::Vec< int, 4 > > var80;
    cv::Vec< float, 4 > var81;
    std::vector< std::vector< cv::Point3_< double > > > var82;
    cv::Vec< int, 2 > var84;
    std::vector< cv::Mat > var85;
    cv::Vec< unsigned short, 3 > var86;
    std::vector< std::vector< cv::Vec< double, 6 > > > var87;
    std::vector< long > var88;
    std::vector< cv::Vec< unsigned char, 3 > > var91;
    std::vector< unsigned char > var93;
    cv::Rect_< int > var96;
    std::vector< std::vector< cv::Vec< short, 4 > > > var97;
    std::vector< cv::Vec< float, 6 > > var98;
    cv::Vec< double, 3 > var102;
    cv::Point_< float > var105;
    std::vector< unsigned long long > var106;
    std::vector< cv::Point_< double > > var107;
    std::vector< std::vector< cv::Vec< short, 3 > > > var109;
    std::vector< std::vector< cv::Point_< double > > > var111;
    std::vector< cv::Point_< int > > var113;
    std::vector< std::vector< cv::Vec< int, 3 > > > var114;
    std::vector< cv::Rect_< int > > var116;
    std::vector< cv::Vec< short, 2 > > var119;
    std::vector< int > var120;
    cv::Scalar_< double > var121;
    cv::Point_< int > var126;
    std::vector< short > var127;
    std::vector< cv::Vec< unsigned short, 2 > > var129;
    std::vector< std::vector< cv::Vec< float, 6 > > > var130;
    cv::Vec< double, 6 > var132;
    cv::Vec< float, 3 > var134;
    cv::Vec< unsigned short, 2 > var138;
    std::vector< long long > var139;
    std::vector< std::vector< cv::Vec< unsigned char, 4 > > > var140;
    std::vector< cv::Vec< short, 3 > > var141;
    std::vector< unsigned long > var142;
    cv::Vec< double, 2 > var144;
    std::vector< std::vector< cv::Vec< float, 2 > > > var145;
    cv::Complex< float > var146;
    std::vector< cv::Vec< unsigned char, 2 > > var147;
    std::vector< CvFuzzyRule* > var150;
    std::vector< CvFuzzyCurve > var153;
    std::vector< cv::Vec< short, 4 > > var156;
    std::vector< cv::Ptr< cv::Mat > > var158;
    cv::Point3_< int > var160;
    std::vector< cv::KDTree::Node > var162;
    std::vector< std::vector< cv::Vec< unsigned char, 2 > > > var166;
    std::vector< std::vector< cv::Vec< unsigned char, 3 > > > var169;
    std::vector< cv::Point3_< int > > var178;
    cv::Vec< unsigned char, 4 > var179;
    std::vector< std::vector< cv::Vec< double, 3 > > > var180;
    std::vector< cv::Vec< int, 2 > > var182;
    cv::Ptr< cv::FilterEngine > var187;
    std::vector< char > var188;
    cv::Vec< int, 4 > var191;
    std::vector< cv::CascadeClassifier::DTreeNode > var194;
    cv::Point3_< double > var195;
    std::vector< std::vector< int > > var198;
    std::vector< cv::Octree::Node > var200;
    std::vector< unsigned int > var202;
    std::vector< std::vector< cv::Vec< double, 4 > > > var203;
    std::vector< std::vector< cv::Vec< float, 4 > > > var204;
    std::vector< std::vector< cv::Point_< float > > > var206;
    std::vector< std::vector< float > > var207;
    std::vector< cv::Vec< unsigned short, 3 > > var209;
};

#endif
