// This file has been generated by Py++.

#include "boost/python.hpp"
#include "sdopencv_wrapper.hpp"
#include "sdopencv_ext_free_functions.pypp.hpp"

namespace bp = boost::python;

void register_free_functions(){

    { //::sdopencv::patchBasedStdDev
    
        typedef void ( *patchBasedStdDev_function_type )( ::cv::Mat const &,::cv::Size const &,::cv::Mat & );
        
        bp::def( 
            "patchBasedStdDev"
            , patchBasedStdDev_function_type( &::sdopencv::patchBasedStdDev )
            , ( bp::arg("in_image"), bp::arg("patch_size"), bp::arg("out_image") ) );
    
    }

    { //::sdopencv::rotateHistToMode
    
        typedef void ( *rotateHistToMode_function_type )( ::std::vector< int > const &,::std::vector< int > & );
        
        bp::def( 
            "rotateHistToMode"
            , rotateHistToMode_function_type( &::sdopencv::rotateHistToMode )
            , ( bp::arg("in_hist"), bp::arg("out_hist") ) );
    
    }

}
