// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "opencv_headers.hpp"
#include "opencv_converters.hpp"
#include "Mat1i.pypp.hpp"

namespace bp = boost::python;

void register_Mat1i_class(){

    { //::cv::Mat_< int >
        typedef bp::class_< cv::Mat_< int >, bp::bases< cv::Mat > > Mat1i_exposer_t;
        Mat1i_exposer_t Mat1i_exposer = Mat1i_exposer_t( "Mat1i", bp::init< >() );
        bp::scope Mat1i_scope( Mat1i_exposer );
        Mat1i_exposer.add_property( "this", pyplus_conv::make_addressof_inst_getter< cv::Mat_< int > >() );
        Mat1i_exposer.def( bp::init< int, int >(( bp::arg("_rows"), bp::arg("_cols") )) );
        Mat1i_exposer.def( bp::init< int, int, int const & >(( bp::arg("_rows"), bp::arg("_cols"), bp::arg("value") )) );
        Mat1i_exposer.def( bp::init< cv::Size_< int > >(( bp::arg("_size") )) );
        bp::implicitly_convertible< cv::Size_< int >, cv::Mat_< int > >();
        Mat1i_exposer.def( bp::init< cv::Size_< int >, int const & >(( bp::arg("_size"), bp::arg("value") )) );
        Mat1i_exposer.def( bp::init< cv::Mat const & >(( bp::arg("m") )) );
        bp::implicitly_convertible< cv::Mat const &, cv::Mat_< int > >();
        Mat1i_exposer.def( bp::init< cv::Mat_< int > const & >(( bp::arg("m") )) );
        Mat1i_exposer.def( bp::init< cv::Mat_< int > const &, cv::Range const &, cv::Range const & >(( bp::arg("m"), bp::arg("rowRange"), bp::arg("colRange") )) );
        Mat1i_exposer.def( bp::init< cv::Mat_< int > const &, cv::Rect_< int > const & >(( bp::arg("m"), bp::arg("roi") )) );
        { //::cv::Mat_< int >::adjustROI
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > & ( exported_class_t::*adjustROI_function_type )( int,int,int,int ) ;
            
            Mat1i_exposer.def( 
                "adjustROI"
                , adjustROI_function_type( &::cv::Mat_< int >::adjustROI )
                , ( bp::arg("dtop"), bp::arg("dbottom"), bp::arg("dleft"), bp::arg("dright") )
                , bp::return_self< >() );
        
        }
        { //::cv::Mat_< int >::channels
        
            typedef cv::Mat_< int > exported_class_t;
            typedef int ( exported_class_t::*channels_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "channels"
                , channels_function_type( &::cv::Mat_< int >::channels ) );
        
        }
        { //::cv::Mat_< int >::clone
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > ( exported_class_t::*clone_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "clone"
                , clone_function_type( &::cv::Mat_< int >::clone ) );
        
        }
        { //::cv::Mat_< int >::col
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > ( exported_class_t::*col_function_type )( int ) const;
            
            Mat1i_exposer.def( 
                "col"
                , col_function_type( &::cv::Mat_< int >::col )
                , ( bp::arg("x") ) );
        
        }
        { //::cv::Mat_< int >::create
        
            typedef cv::Mat_< int > exported_class_t;
            typedef void ( exported_class_t::*create_function_type )( int,int ) ;
            
            Mat1i_exposer.def( 
                "create"
                , create_function_type( &::cv::Mat_< int >::create )
                , ( bp::arg("_rows"), bp::arg("_cols") ) );
        
        }
        { //::cv::Mat_< int >::create
        
            typedef cv::Mat_< int > exported_class_t;
            typedef void ( exported_class_t::*create_function_type )( ::cv::Size_< int > ) ;
            
            Mat1i_exposer.def( 
                "create"
                , create_function_type( &::cv::Mat_< int >::create )
                , ( bp::arg("_size") ) );
        
        }
        { //::cv::Mat_< int >::cross
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > ( exported_class_t::*cross_function_type )( ::cv::Mat_< int > const & ) const;
            
            Mat1i_exposer.def( 
                "cross"
                , cross_function_type( &::cv::Mat_< int >::cross )
                , ( bp::arg("m") ) );
        
        }
        { //::cv::Mat_< int >::depth
        
            typedef cv::Mat_< int > exported_class_t;
            typedef int ( exported_class_t::*depth_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "depth"
                , depth_function_type( &::cv::Mat_< int >::depth ) );
        
        }
        { //::cv::Mat_< int >::diag
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > ( exported_class_t::*diag_function_type )( int ) const;
            
            Mat1i_exposer.def( 
                "diag"
                , diag_function_type( &::cv::Mat_< int >::diag )
                , ( bp::arg("d")=(int)(0) ) );
        
        }
        { //::cv::Mat_< int >::elemSize
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::size_t ( exported_class_t::*elemSize_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "elemSize"
                , elemSize_function_type( &::cv::Mat_< int >::elemSize ) );
        
        }
        { //::cv::Mat_< int >::elemSize1
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::size_t ( exported_class_t::*elemSize1_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "elemSize1"
                , elemSize1_function_type( &::cv::Mat_< int >::elemSize1 ) );
        
        }
        { //::cv::Mat_< int >::reshape
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > ( exported_class_t::*reshape_function_type )( int ) const;
            
            Mat1i_exposer.def( 
                "reshape"
                , reshape_function_type( &::cv::Mat_< int >::reshape )
                , ( bp::arg("_rows") ) );
        
        }
        { //::cv::Mat_< int >::row
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::cv::Mat_< int > ( exported_class_t::*row_function_type )( int ) const;
            
            Mat1i_exposer.def( 
                "row"
                , row_function_type( &::cv::Mat_< int >::row )
                , ( bp::arg("y") ) );
        
        }
        { //::cv::Mat_< int >::step1
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::size_t ( exported_class_t::*step1_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "step1"
                , step1_function_type( &::cv::Mat_< int >::step1 ) );
        
        }
        { //::cv::Mat_< int >::stepT
        
            typedef cv::Mat_< int > exported_class_t;
            typedef ::size_t ( exported_class_t::*stepT_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "stepT"
                , stepT_function_type( &::cv::Mat_< int >::stepT ) );
        
        }
        { //::cv::Mat_< int >::type
        
            typedef cv::Mat_< int > exported_class_t;
            typedef int ( exported_class_t::*type_function_type )(  ) const;
            
            Mat1i_exposer.def( 
                "type"
                , type_function_type( &::cv::Mat_< int >::type ) );
        
        }
    }

}
