// This file has been generated by Py++.

#ifndef sdopencv_ext_classes_1_hpp__pyplusplus_wrapper
#define sdopencv_ext_classes_1_hpp__pyplusplus_wrapper

void register_classes_1();

#endif//sdopencv_ext_classes_1_hpp__pyplusplus_wrapper
