// This file has been generated by Py++.

#ifndef vector_Vec4i_hpp__pyplusplus_wrapper
#define vector_Vec4i_hpp__pyplusplus_wrapper

void register_vector_Vec4i_class();

#endif//vector_Vec4i_hpp__pyplusplus_wrapper
