// This file has been generated by Py++.

#ifndef vector_CvFuzzyCurve_hpp__pyplusplus_wrapper
#define vector_CvFuzzyCurve_hpp__pyplusplus_wrapper

void register_vector_CvFuzzyCurve_class();

#endif//vector_CvFuzzyCurve_hpp__pyplusplus_wrapper
