// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "opencv_headers.hpp"
#include "vector_MatND.pypp.hpp"

namespace bp = boost::python;

static inline void resize(::std::vector< cv::MatND > &inst, size_t num) { inst.resize(num); }

void register_vector_MatND_class(){

    { //::std::vector< cv::MatND >
        typedef bp::class_< std::vector< cv::MatND > > vector_MatND_exposer_t;
        vector_MatND_exposer_t vector_MatND_exposer = vector_MatND_exposer_t( "vector_MatND" );
        bp::scope vector_MatND_scope( vector_MatND_exposer );
        //WARNING: the next line of code will not compile, because "::cv::MatND" does not have operator== !
        vector_MatND_exposer.def( bp::vector_indexing_suite< ::std::vector< cv::MatND > >() );
        vector_MatND_exposer.def("resize", &::resize, ( bp::arg("num") ));
    }

}
