// This file has been generated by Py++.

#ifndef vector_uint64_hpp__pyplusplus_wrapper
#define vector_uint64_hpp__pyplusplus_wrapper

void register_vector_uint64_class();

#endif//vector_uint64_hpp__pyplusplus_wrapper
