// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "opencv_headers.hpp"
#include "CvSize.pypp.hpp"

namespace bp = boost::python;

void register_CvSize_class(){

    bp::class_< CvSize >( "CvSize", "\nPixel-accurate size of a rectangle."
    "\nReference:"
    "\n    http://opencv.willowgarage.com/documentation/basic_structures.html#cvsize" )    
        .add_property( "this", pyplus_conv::make_addressof_inst_getter< CvSize >(), "\nPixel-accurate size of a rectangle."
    "\nReference:"
    "\n    http://opencv.willowgarage.com/documentation/basic_structures.html#cvsize" )    
        .def_readwrite( "height", &CvSize::height )    
        .def_readwrite( "width", &CvSize::width );

}
