#ifndef SD_TEMPLATE_INSTANTIATIONS_HPP
#define SD_TEMPLATE_INSTANTIATIONS_HPP

class dummy_struct {
public:
    struct dummy_struct2 {};
    static const int total_size = 0
        + sizeof(std::vector<long>)
        + sizeof(std::vector<cv::Octree::Node>)
        + sizeof(std::vector<cv::Vec<int,3> >)
        + sizeof(std::vector<cv::Vec<float,2> >)
        + sizeof(std::vector<cv::Vec<unsigned char,4> >)
        + sizeof(std::vector<cv::Vec<unsigned short,3> >)
        + sizeof(std::vector<double>)
        + sizeof(std::vector<cv::Size_<float> >)
        + sizeof(std::vector<cv::CascadeClassifier::Stage>)
        + sizeof(cv::Point3_<int>)
        + sizeof(std::vector<cv::Vec<double,2> >)
        + sizeof(std::vector<unsigned short>)
        + sizeof(std::vector<cv::Vec<float,4> >)
        + sizeof(std::vector<cv::Point3_<int> >)
        + sizeof(std::vector<cv::Vec<unsigned short,4> >)
        + sizeof(cv::Size_<int>)
        + sizeof(cv::Vec<double,4>)
        + sizeof(std::vector<cv::FernClassifier::Feature>)
        + sizeof(cv::Vec<float,3>)
        + sizeof(std::vector<cv::Point_<float> >)
        + sizeof(std::vector<float>)
        + sizeof(cv::Seq<CvSURFPoint>)
        + sizeof(cv::Vec<unsigned short,2>)
        + sizeof(std::vector<int>)
        + sizeof(std::vector<unsigned long long>)
        + sizeof(std::vector<cv::Point3_<double> >)
        + sizeof(std::vector<cv::Vec<double,3> >)
        + sizeof(std::vector<unsigned int>)
        + sizeof(std::vector<CvFuzzyRule*>)
        + sizeof(cv::Ptr<cv::FeatureEvaluator>)
        + sizeof(cv::Point_<double>)
        + sizeof(cv::Point3_<double>)
        + sizeof(cv::Vec<double,2>)
        + sizeof(cv::Vec<short,3>)
        + sizeof(std::vector<CvFuzzyCurve>)
        + sizeof(cv::Vec<unsigned short,3>)
        + sizeof(std::vector<std::vector<int> >)
        + sizeof(std::vector<unsigned char>)
        + sizeof(std::vector<cv::RotatedRect>)
        + sizeof(std::vector<std::vector<cv::Point_<float> > >)
        + sizeof(std::vector<cv::Vec<short,3> >)
        + sizeof(cv::Vec<unsigned char,2>)
        + sizeof(cv::Vec<int,2>)
        + sizeof(cv::Vec<double,3>)
        + sizeof(cv::Vec<short,2>)
        + sizeof(std::vector<cv::Point_<int> >)
        + sizeof(std::vector<unsigned long>)
        + sizeof(std::vector<cv::Vec<unsigned char,2> >)
        + sizeof(cv::Vec<float,2>)
        + sizeof(std::vector<cv::Vec<float,6> >)
        + sizeof(std::vector<std::vector<cv::Vec<int,2> > >)
        + sizeof(std::vector<std::vector<cv::Point3_<int> > >)
        + sizeof(cv::Rect_<int>)
        + sizeof(cv::Ptr<cv::BaseFilter>)
        + sizeof(cv::Vec<unsigned char,4>)
        + sizeof(cv::Ptr<CvStereoBMState>)
        + sizeof(std::vector<cv::Size_<int> >)
        + sizeof(std::vector<std::vector<float> >)
        + sizeof(cv::Vec<unsigned char,3>)
        + sizeof(cv::Vec<int,3>)
        + sizeof(cv::Point_<float>)
        + sizeof(cv::Size_<float>)
        + sizeof(std::vector<cv::CascadeClassifier::DTreeNode>)
        + sizeof(std::vector<std::vector<cv::Point_<double> > >)
        + sizeof(cv::Complex<double>)
        + sizeof(std::vector<char>)
        + sizeof(std::vector<cv::Rect_<int> >)
        + sizeof(std::vector<cv::Vec<int,2> >)
        + sizeof(std::vector<cv::Vec<unsigned short,2> >)
        + sizeof(std::vector<std::vector<cv::Point3_<double> > >)
        + sizeof(std::vector<short>)
        + sizeof(std::vector<cv::Vec<float,3> >)
        + sizeof(cv::Complex<float>)
        + sizeof(std::vector<cv::Ptr<cv::Mat> >)
        + sizeof(cv::Vec<short,4>)
        + sizeof(cv::Vec<int,4>)
        + sizeof(cv::Ptr<cv::Mat>)
        + sizeof(cv::Vec<float,4>)
        + sizeof(cv::Point_<int>)
        + sizeof(std::vector<cv::Vec<double,4> >)
        + sizeof(std::vector<cv::Vec<int,4> >)
        + sizeof(cv::Vec<double,6>)
        + sizeof(std::vector<cv::Vec<double,6> >)
        + sizeof(std::vector<cv::KDTree::Node>)
        + sizeof(std::vector<cv::KeyPoint>)
        + sizeof(std::vector<cv::Vec<short,4> >)
        + sizeof(std::vector<cv::Mat>)
        + sizeof(std::vector<cv::Vec<short,2> >)
        + sizeof(std::vector<cv::Point3_<float> >)
        + sizeof(std::vector<cv::Scalar_<double> >)
        + sizeof(cv::Ptr<CvHaarClassifierCascade>)
        + sizeof(cv::Ptr<cv::BaseColumnFilter>)
        + sizeof(std::vector<cv::MatND>)
        + sizeof(std::vector<long long>)
        + sizeof(std::vector<cv::Vec<unsigned char,3> >)
        + sizeof(cv::Point3_<float>)
        + sizeof(cv::Scalar_<double>)
        + sizeof(cv::Vec<float,6>)
        + sizeof(std::vector<unsigned char *>)
        + sizeof(std::vector<cv::Range>)
        + sizeof(cv::Ptr<cv::FilterEngine>)
        + sizeof(cv::Ptr<CvMemStorage>)
        + sizeof(std::vector<cv::Point_<double> >)
        + sizeof(std::vector<cv::CascadeClassifier::DTree>)
        + sizeof(cv::Vec<unsigned short,4>)
        + sizeof(cv::Ptr<cv::BaseRowFilter>)
        + sizeof(std::vector<std::vector<cv::Point_<int> > >)
        + sizeof(std::vector<std::vector<cv::Point3_<float> > >);
};

#endif
