// This file has been generated by Py++.

#include "boost/python.hpp"
#include "__ctypes_integration.pypp.hpp"
#include "opencv_headers.hpp"
#include "CvLevMarq.pypp.hpp"

namespace bp = boost::python;

void register_CvLevMarq_class(){

    bp::class_< CvLevMarq >( "CvLevMarq" )    
        .add_property( "this", pyplus_conv::make_addressof_inst_getter< CvLevMarq >() );

}
