// This file has been generated by Py++.

#ifndef unbounded_array_float32_hpp__pyplusplus_wrapper
#define unbounded_array_float32_hpp__pyplusplus_wrapper

void register_unbounded_array_float32_class();

#endif//unbounded_array_float32_hpp__pyplusplus_wrapper
