// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "opencv_headers.hpp"
#include "vector_int64.pypp.hpp"

namespace bp = boost::python;

static inline void resize(::std::vector< long long > &inst, size_t num) { inst.resize(num); }

void register_vector_int64_class(){

    { //::std::vector< long long >
        typedef bp::class_< std::vector< long long > > vector_int64_exposer_t;
        vector_int64_exposer_t vector_int64_exposer = vector_int64_exposer_t( "vector_int64" );
        bp::scope vector_int64_scope( vector_int64_exposer );
        vector_int64_exposer.def( bp::vector_indexing_suite< ::std::vector< long long >, true >() );
        vector_int64_exposer.def("resize", &::resize, ( bp::arg("num") ));
    }

}
