// This file has been generated by Py++.

#ifndef __stl_dummy_struct_hpp__pyplusplus_wrapper
#define __stl_dummy_struct_hpp__pyplusplus_wrapper

void register___stl_dummy_struct_class();

#endif//__stl_dummy_struct_hpp__pyplusplus_wrapper
