#ifndef SD_highgui_TEMPLATE_INSTANTIATIONS_HPP
#define SD_highgui_TEMPLATE_INSTANTIATIONS_HPP

class highgui_dummy_struct {
public:
    struct dummy_struct2 {};
    static const int total_size = 0
        + sizeof(cv::Complex<double>)
        + sizeof(cv::Complex<float>)
        + sizeof(cv::Point3_<double>)
        + sizeof(cv::Point3_<float>)
        + sizeof(cv::Point3_<int>)
        + sizeof(cv::Point_<double>)
        + sizeof(cv::Point_<float>)
        + sizeof(cv::Point_<int>)
        + sizeof(cv::Ptr<CvMemStorage>)
        + sizeof(cv::Ptr<cv::Mat>)
        + sizeof(cv::Rect_<int>)
        + sizeof(cv::Scalar_<double>)
        + sizeof(cv::Seq<cv::Point_<int> >)
        + sizeof(cv::Seq<int>)
        + sizeof(cv::Size_<float>)
        + sizeof(cv::Size_<int>)
        + sizeof(cv::Vec<double,2>)
        + sizeof(cv::Vec<double,3>)
        + sizeof(cv::Vec<double,4>)
        + sizeof(cv::Vec<double,6>)
        + sizeof(cv::Vec<float,2>)
        + sizeof(cv::Vec<float,3>)
        + sizeof(cv::Vec<float,4>)
        + sizeof(cv::Vec<float,6>)
        + sizeof(cv::Vec<int,2>)
        + sizeof(cv::Vec<int,3>)
        + sizeof(cv::Vec<int,4>)
        + sizeof(cv::Vec<short,2>)
        + sizeof(cv::Vec<short,3>)
        + sizeof(cv::Vec<short,4>)
        + sizeof(cv::Vec<unsigned char,2>)
        + sizeof(cv::Vec<unsigned char,3>)
        + sizeof(cv::Vec<unsigned char,4>)
        + sizeof(cv::Vec<unsigned short,2>)
        + sizeof(cv::Vec<unsigned short,3>)
        + sizeof(cv::Vec<unsigned short,4>)
        + sizeof(std::vector<char>)
        + sizeof(std::vector<cv::KDTree::Node>)
        + sizeof(std::vector<cv::Mat>)
        + sizeof(std::vector<cv::MatND>)
        + sizeof(std::vector<cv::Point3_<double> >)
        + sizeof(std::vector<cv::Point3_<float> >)
        + sizeof(std::vector<cv::Point3_<int> >)
        + sizeof(std::vector<cv::Point_<double> >)
        + sizeof(std::vector<cv::Point_<float> >)
        + sizeof(std::vector<cv::Point_<int> >)
        + sizeof(std::vector<cv::Ptr<cv::Mat> >)
        + sizeof(std::vector<cv::Range>)
        + sizeof(std::vector<cv::Rect_<int> >)
        + sizeof(std::vector<cv::RotatedRect>)
        + sizeof(std::vector<cv::Scalar_<double> >)
        + sizeof(std::vector<cv::Size_<float> >)
        + sizeof(std::vector<cv::Size_<int> >)
        + sizeof(std::vector<cv::Vec<double,2> >)
        + sizeof(std::vector<cv::Vec<double,3> >)
        + sizeof(std::vector<cv::Vec<double,4> >)
        + sizeof(std::vector<cv::Vec<double,6> >)
        + sizeof(std::vector<cv::Vec<float,2> >)
        + sizeof(std::vector<cv::Vec<float,3> >)
        + sizeof(std::vector<cv::Vec<float,4> >)
        + sizeof(std::vector<cv::Vec<float,6> >)
        + sizeof(std::vector<cv::Vec<int,2> >)
        + sizeof(std::vector<cv::Vec<int,3> >)
        + sizeof(std::vector<cv::Vec<int,4> >)
        + sizeof(std::vector<cv::Vec<short,2> >)
        + sizeof(std::vector<cv::Vec<short,3> >)
        + sizeof(std::vector<cv::Vec<short,4> >)
        + sizeof(std::vector<cv::Vec<unsigned char,2> >)
        + sizeof(std::vector<cv::Vec<unsigned char,3> >)
        + sizeof(std::vector<cv::Vec<unsigned char,4> >)
        + sizeof(std::vector<cv::Vec<unsigned short,2> >)
        + sizeof(std::vector<cv::Vec<unsigned short,3> >)
        + sizeof(std::vector<cv::Vec<unsigned short,4> >)
        + sizeof(std::vector<double>)
        + sizeof(std::vector<float>)
        + sizeof(std::vector<int>)
        + sizeof(std::vector<long long>)
        + sizeof(std::vector<long>)
        + sizeof(std::vector<short>)
        + sizeof(std::vector<std::vector<cv::Point3_<double> > >)
        + sizeof(std::vector<std::vector<cv::Point3_<float> > >)
        + sizeof(std::vector<std::vector<cv::Point3_<int> > >)
        + sizeof(std::vector<std::vector<cv::Point_<double> > >)
        + sizeof(std::vector<std::vector<cv::Point_<float> > >)
        + sizeof(std::vector<std::vector<cv::Point_<int> > >)
        + sizeof(std::vector<std::vector<cv::Vec<int,2> > >)
        + sizeof(std::vector<std::vector<float> >)
        + sizeof(std::vector<std::vector<int> >)
        + sizeof(std::vector<unsigned char *>)
        + sizeof(std::vector<unsigned char>)
        + sizeof(std::vector<unsigned int>)
        + sizeof(std::vector<unsigned long long>)
        + sizeof(std::vector<unsigned long>)
        + sizeof(std::vector<unsigned short>);
};

#endif
