// This file has been generated by Py++.

#ifndef ml_ext_classes_1_hpp__pyplusplus_wrapper
#define ml_ext_classes_1_hpp__pyplusplus_wrapper

void register_classes_1();

#endif//ml_ext_classes_1_hpp__pyplusplus_wrapper
